# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bhanu Teja Gullapalli
full_name: Bhanu Teja Gullapalli
email: bhanutejaiit@gmail.com
email2: bgullapalli@ucsd.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bhanutejagullapalli.github.io/" # the base hostname & protocol for your site
github_username:  BhanuTejaGullapalli
twitter_username: BhanuGullapalli
linkedin_username: bhanu-teja-gullapalli

include: ['_pages']


# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
